#!/bin/bash
  
E_BADARGS=65
MYSQL=`which mysql`
DB_NAME="OF_IDPS"
DB_USER="root"
DB_PASSWORD="123mudar"
  
Q1="CREATE DATABASE IF NOT EXISTS $DB_NAME;"
Q2="GRANT USAGE ON *.* TO $DB_USER@'%' IDENTIFIED BY '$DB_PASSWORD';"
Q3="GRANT ALL PRIVILEGES ON $DB_NAME.* TO $DB_PASSWORD@'%';"
Q4="FLUSH PRIVILEGES;"
SQL="${Q1}${Q2}${Q3}${Q4}"
    
$MYSQL -uroot -p -e "$SQL"