#!/bin/bash

ipController="192.168.2.111"
portController="6633"
bridge="xenbr0"

start() {
        echo -n $"Starting setting OpenFlow controller on IP $ipController port $portController"
	ovs-vsctl set-controller $bridge tcp:$ipController:$portController
}

stop() {
        echo -n $"Stopping remove ip controller $ipController and put on standalone mode"
	ovs-vsctl del-controller $bridge
}

restart(){
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	restart
        ;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	RETVAL=1
esac

exit $RETVAL
