create table flows(
		swID long not null,
                tempo datetime,
                byteCount long,
                cookie long,
                durationNanoseconds int,
                durationSeconds int,
                hardTimeout int,
                idleTimeout int,
                length int,
                packetCount long,
                priority int,
                tableId int,
                dataLayerDestination blob,
                dataLayerSource blob,
                dataLayerType int,
                dataLayerVirtualLan int,
                dataLayerVirtualLanPriorityCodePoint int,
                inputPort int,
                networkDestination int,
                networkProtocol int,
                networkSource int,
                networkTypeOfService int,
                transportDestination int,
                transportSource int, 
                Wildcards int
 );
